# -*- coding: utf-8 -*-
"""original

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HksK1akM-WV1e_69xeDhOL_dFbqa_lK

# Human Biomechanic Analysis

## Import necessary libraries
"""

import pandas as pd
import numpy as np
import os
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelBinarizer
from google.colab import drive

"""## Mount Drive & Load Dataset"""

!ls "/content/drive/MyDrive/daphnet+freezing+of+gait (1)/dataset_fog_release/dataset/"

from google.colab import drive
drive.mount('/content/drive')

dataset_dir = "/content/drive/MyDrive/gait dataset/"
dataset_zip = dataset_dir + "gait-in-parkinsons-disease-1.0.0.zip"

!unzip -q "$dataset_zip"

from google.colab import drive
drive.mount('/content/drive')

"""## Convert to CSV format"""

!rm -r CSV
!rm -r Final

!cp -r gait-in-parkinsons-disease-1.0.0 Physionet
!rm -r CSV
!rm -r Final

!mv gait-in-parkinsons-disease-1.0.0 Physionet
len(os.listdir('Physionet'))

features = ['Time', 'L1' , 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8',
            'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8',
            'Total_Force_Left', 'Total_Force_Right']

!mkdir CSV

# reading given csv file
# and creating dataframe
for name in os.listdir('Physionet'):
  if 'Co' in name or 'Pt' in name:
    # print(name)
    df = pd.read_csv('Physionet/' + name, header = None, sep='\t')

    # adding column headings
    df.columns = features

    # store dataframe into csv file
    name = 'CSV/' + name.split('.')[0]+'.csv'
    # print(name)
    df.to_csv(name, index = None)

from google.colab import files
import os

# Zip the CSV directory
os.system("zip -r CSV.zip CSV")

# Move the zip file to the content folder
os.system("mv CSV.zip /content/CSV.zip")

# Specify the local path where you want to download the files
local_download_path = r"D:\Newfolder\s7\project\gait csv"

# Create the local download path if it doesn't exist
os.makedirs(local_download_path, exist_ok=True)

# Unzip the CSV files
os.system(f"unzip -q /content/CSV.zip -d {local_download_path}")

# Download all CSV files to your local machine
for csv_file in os.listdir(local_download_path):
    files.download(os.path.join(local_download_path, csv_file))

"""## Data Visualization"""

pd_subject = 'GaPt03_01'
control_subject = 'GaCo01_01'

pd_df = pd.read_csv('CSV/' + pd_subject + '.csv').head(1001)
control_df = pd.read_csv('CSV/' + control_subject + '.csv').head(1001)
print(pd_df.shape)
print(control_df.shape)

nrows = 1
ncols = 2

fig = plt.gcf()
fig.set_size_inches(ncols * 5, nrows * 5)

for i, fname in enumerate(['Total_Force_Left', 'Total_Force_Right']):
  plt.subplot(nrows, ncols, i+1)
  plt.tight_layout()
  plt.title("Time vs " + fname)
  plt.plot(control_df.Time, control_df[fname])
  plt.plot(pd_df.Time, pd_df[fname])
  plt.xlabel('Time (in seconds)')

plt.legend(["Control", "PD",])
plt.show()

nrows = 2
ncols = 4
subjects = ['GaCo03_01', 'GaPt06_01', 'GaPt04_01', 'GaPt03_01']
category = ['Healthy Control', 'PD Severity 2', 'PD Severity 2.5', 'PD Severity 3']
colors = ['blue', '#FFD600', 'orange', 'red']
fig = plt.gcf()
fig.set_size_inches(ncols * 4, nrows * 4)

i = 0
for sub in subjects:
  df = pd.read_csv('CSV/' + sub + '.csv').head(1001)
  i += 1
  for j, fname in enumerate(['Total_Force_Left', 'Total_Force_Right']):
    plt.subplot(nrows, ncols, i + (j*4))
    plt.tight_layout()
    plt.plot(df.Time, df[fname], color=colors[i-1])
    plt.xlabel('Time (in seconds)')
    plt.ylabel(fname)
    plt.title(category[i-1])

plt.show()

"""## Preprocess the dataset

### Demographics
"""

demographics = pd.read_csv('Physionet/demographics.txt', delim_whitespace=True)
sub_id = demographics.ID.to_list()
sub_names = []
for name in os.listdir('CSV'):
  sub_name = name.split('_')[0]
  sub_names.append(sub_name)

print("Subjects Count (in demographics) = ", len(sub_id))
print("Files count = ", len(sub_names))

"""### Preprocessing HoehnYahr Feature
- Filling the missing data
- Changing the classes

| HY Score | Class |
|----------|-------|
| 0.0 | 0 |
| 2.5 | 1 |
| 2.0 | 2 |
| 3.0 | 3 |
"""

demographics.HoehnYahr
demographics['HoehnYahr'] = demographics['HoehnYahr'].fillna(0)
demographics.HoehnYahr.value_counts()

# Remove the demographics of missing file
demographics = demographics[demographics.ID != 'Juc010']
print("Subject Count from different Study")
print(demographics.Study.value_counts())

print("\nSubject Count - Study & Gender")
print(pd.crosstab(demographics.Study, demographics.Gender))

print("\nSubject Count - Study & Groups")
print(pd.crosstab(demographics.Study, demographics.Group))

print("\nSubject Count - Groups & Gender")
print(pd.crosstab(demographics.Group, demographics.Gender))

print("\nSubject Count - Study + Groups & Gender")
print(pd.crosstab([demographics.Study, demographics.Group], demographics.Gender))

print("\nSubject Count - Study Group & HoehnYahr Severity")
print(pd.crosstab(demographics.Study, demographics.HoehnYahr))

demographics['HoehnYahr'].replace({2.5: 1}, inplace=True)
demographics['HoehnYahr'] = demographics['HoehnYahr'].astype(int)
demographics.HoehnYahr.value_counts()

"""## Segmentation of the Data
- Each segment will be of the shape 100 x 19
"""

!mkdir Final
!mkdir Final/train
!mkdir Final/test

count = len(os.listdir('CSV'))
train_count = int(70/100*count)
test_count = count - train_count

print("Training Count Subjects = ", train_count)
print("Test Count Subjects = ", test_count)

category = 'train'
counter = 1

ypath = 'Final/y_' + category + '.txt'
yfile = open(ypath, "a")
hypath = 'Final/hyscore_' + category + '.txt'
hyfile = open(hypath, "a")

for name in os.listdir('CSV'):
  if counter == train_count + 1:
    yfile.flush()
    yfile.close()
    hyfile.flush()
    hyfile.close()

    category = 'test'
    ypath = 'Final/y_' + category + '.txt'
    yfile = open(ypath, "a")
    hypath = 'Final/hyscore_' + category + '.txt'
    hyfile = open(hypath, "a")
  print(counter, name, category)

  sub_name = name.split('_')[0]
  sub_class = demographics[demographics['ID'] == sub_name]['Group'].to_string(index=False).strip()
  hy_class = demographics[demographics['ID'] == sub_name]['HoehnYahr'].to_string(index=False).strip()
  sub_data = pd.read_csv('CSV/' + name)
  features = sub_data.columns.to_list()

  full_size = 100
  overlap = 0.5
  overlap_size = int(full_size * overlap / 2)
  entry_size = full_size - overlap_size

  for i in range(0, sub_data.shape[0], entry_size):
    if sub_data.shape[0] >= i + entry_size + overlap_size:
      yfile.write(sub_class + "\n")
      hyfile.write(hy_class + "\n")

      for fname in features:
        path_name = 'Final/' + category + '/'
        file_name = fname + '_' + category + '.txt'
        with open(path_name + file_name, 'a') as feat_file:
          arr = sub_data.iloc[i:i + entry_size + overlap_size, ][fname].to_numpy()
          # print(i, len(arr), end = ' | ')
          feat_file.write(' '.join(map(str, arr)) + "\n")

  counter = counter + 1
yfile.flush()
yfile.close()
hyfile.flush()
yfile.close()

"""## Load Dataset - Training and Testing"""

def load_file(filepath):
	dataframe = pd.read_csv(filepath, header=None, delim_whitespace=True)
	return dataframe.values

# load a list of files into a 3D array of [samples, timesteps, features]
def load_category(filenames, prefix=''):
	loaded = list()
	for name in filenames:
		data = load_file(prefix + name)
		loaded.append(data)
	# stack group so that features are the 3rd dimension
	loaded = np.dstack(loaded)
	return loaded


# load a dataset category, such as train or test
def load_dataset_category(category, prefix=''):
	# load all 19 files as a single array
	filenames = []
	for fname in features:
		filenames.append(category + '/' + fname + '_' + category + '.txt')

	# load input data
	X = load_category(filenames, prefix)
	# load class output
	y = load_file(prefix + 'y_'+ category +'.txt')
	hy = load_file(prefix + 'hyscore_'+ category +'.txt')
	return X, y, hy

# load the dataset, returns train and test X and y elements
def load_dataset(prefix=''):
	# load all train
	trainX, trainy, trainHY = load_dataset_category('train', prefix)
	print(trainX.shape, trainy.shape, trainHY.shape)
	# load all test
	testX, testy, testHY = load_dataset_category('test', prefix)
	print(testX.shape, testy.shape, testHY.shape)

	# zero-offset class values
	trainy = trainy - 1
	testy = testy - 1
	# one hot encode y
	trainy = tf.keras.utils.to_categorical(trainy)
	trainHY = tf.keras.utils.to_categorical(trainHY)
	testy = tf.keras.utils.to_categorical(testy)
	testHY = tf.keras.utils.to_categorical(testHY)

	# print(trainX.shape, trainy.shape, trainHY.shape, testX.shape, testy.shape, testHY.shape)
	return trainX, trainy, trainHY, testX, testy, testHY

trainX, trainy, trainHY, testX, testy, testHY = load_dataset('Final/')
print("Training Data = ", trainX.shape)
print("Training Class = ", trainy.shape)
print("Training HoehnYahr Class = ", trainHY.shape)
print("Test Data = ", testX.shape)
print("Test Class = ", testy.shape)
print("Test HoehnYahr Class = ", testHY.shape)

"""## Detection of PD
- PD - 0
- Control - 1

### PD Model
"""

verbose, epochs, batch_size = 1, 500, 32
n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]

DESIRED_ACCURACY = 0.97

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if logs.get('accuracy') > DESIRED_ACCURACY:
      print("Reached " + str(DESIRED_ACCURACY*100)  + "% accuracy so cancelling training!")
      self.model.stop_training = True

callbacks = myCallback()

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(n_timesteps,n_features)))
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.Dense(n_outputs, activation='softmax'))

model.compile(loss = 'binary_crossentropy',
              optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics =[tf.keras.metrics.TruePositives(name='tp'),
                        tf.keras.metrics.FalsePositives(name='fp'),
                        tf.keras.metrics.TrueNegatives(name='tn'),
                        tf.keras.metrics.FalseNegatives(name='fn'),
                        'accuracy',
                        tf.keras.metrics.Precision(name='precision'),
                        tf.keras.metrics.Recall(name='recall'),
                        tf.keras.metrics.AUC(name='auc')])
model.summary()

"""### Train the model"""

with tf.device('/device:GPU:0'):
  PD_history = model.fit(trainX,
                        trainy,
                        validation_data=(testX, testy),
                        epochs = epochs,
                        batch_size = batch_size,
                        verbose = verbose,
                        callbacks = [callbacks])

"""### Save the Model"""

model.save("/content/drive/MyDrive/College Related/Project Work 1 - Sem 7/Saved Models/PD_Model.h5")
print("PD_Model saved Successfully!")

model = tf.keras.models.load_model("/content/drive/MyDrive/College Related/Project Work 1 - Sem 7/Saved Models/PD_Model.h5")

"""### Plot the graphs"""

# Plot the accuracy and loss functions
def plot_graphs(history, string):
  plt.plot(history.history[string])
  plt.plot(history.history['val_'+string])
  plt.xlabel("Epochs")
  plt.ylabel(string)
  plt.legend([string, 'val_'+string])
  plt.title('Training and Validation ' + string)
  plt.show()

plot_graphs(PD_history, "accuracy")
plot_graphs(PD_history, "loss")

"""### Evaluation of Model"""

def model_evaluate(model, target, testX, testy):
  y_pred = model.predict(testX)
  y_pred = np.argmax(y_pred, axis=1)
  y_test = np.argmax(testy, axis=1)

  # Confusion matrix
  print('Confusion Matrix')

  cm = tf.math.confusion_matrix(labels = y_test, predictions = y_pred)
  # Calculate accuracy
  cm_np = cm.numpy()
  conf_acc = accuracy_score(y_test, y_pred) * 100
  print("Accuracy for Test Data = ", conf_acc)

  plt.figure(figsize = (12,8))
  seaborn.heatmap(cm, annot=True, fmt='d')
  plt.title("Confusion Matrix for Test Data")
  plt.xlabel('Predicted')
  plt.ylabel('Expected')
  plt.show()

  # Classification Report
  print('\nClassification Report')
  print(classification_report(y_test, y_pred))


  # Precision vs Recall Curve
  print('\nPrecision vs Recall Curve')
  fig, c_ax = plt.subplots(1,1, figsize = (12, 8))

  y_test = tf.keras.utils.to_categorical(y_test)
  y_pred = tf.keras.utils.to_categorical(y_pred)
  n_classes = 2

  precision = dict()
  recall = dict()

  for i in range(n_classes):
    precision[i], recall[i], _ = precision_recall_curve(y_test[:, i],
                                                          y_pred[:, i])
    plt.plot(recall[i], precision[i], lw=2, label='class {}'.format(i))

  plt.xlabel("recall")
  plt.ylabel("precision")
  plt.legend(loc="best")
  plt.title("Precision vs. Recall curve")
  plt.show()

  # ROC Curve
  print('\nROC Curve')
  average = 'macro'
  fig, c_ax = plt.subplots(1,1, figsize = (12, 8))
  for (idx, c_label) in enumerate(target):
      fpr, tpr, thresholds = roc_curve(y_test[:,idx].astype(int), y_pred[:,idx])
      c_ax.plot(fpr, tpr, label = '%s (AUC:%0.2f)'  % (c_label, auc(fpr, tpr)))
  c_ax.plot(fpr, fpr, 'b-', label = 'Random Guessing')
  print('ROC AUC score:', roc_auc_score(y_test, y_pred, average=average))

  c_ax.legend()
  c_ax.set_xlabel('False Positive Rate')
  c_ax.set_ylabel('True Positive Rate')
  plt.title('ROC Curve')
  plt.show()

model_evaluate(model, [0,1], testX, testy)

"""## Classification based on HoehnYahr Score

### HY Model
"""

verbose, epochs, batch_size = 1, 500, 32
n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainHY.shape[1]

callbacks = myCallback()
HYmodel = tf.keras.models.Sequential()
HYmodel.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(n_timesteps,n_features)))
HYmodel.add(tf.keras.layers.MaxPooling1D(pool_size=2))
HYmodel.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu'))
HYmodel.add(tf.keras.layers.MaxPooling1D(pool_size=2))
HYmodel.add(tf.keras.layers.Dropout(0.5))
HYmodel.add(tf.keras.layers.Flatten())
HYmodel.add(tf.keras.layers.Dense(100, activation='relu'))
HYmodel.add(tf.keras.layers.Dense(n_outputs, activation='softmax'))

HYmodel.compile(loss = 'categorical_crossentropy',
              optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001),
              metrics =[tf.keras.metrics.TruePositives(name='tp'),
                        tf.keras.metrics.FalsePositives(name='fp'),
                        tf.keras.metrics.TrueNegatives(name='tn'),
                        tf.keras.metrics.FalseNegatives(name='fn'),
                        'accuracy',
                        tf.keras.metrics.Precision(name='precision'),
                        tf.keras.metrics.Recall(name='recall'),
                        tf.keras.metrics.AUC(name='auc')])
HYmodel.summary()

"""### Train the model"""

with tf.device('/device:GPU:0'):
  HY_history = HYmodel.fit(trainX,
                          trainHY,
                          validation_data=(testX, testHY),
                          epochs = epochs,
                          batch_size = batch_size,
                          verbose = verbose,
                          callbacks = [callbacks])

"""### Save the model"""

HYmodel.save("/content/drive/MyDrive/College Related/Project Work 1 - Sem 7/Saved Models/HY_Model.h5")
print("HY_Model saved Successfully!")

HYmodel = tf.keras.models.load_model("/content/drive/MyDrive/College Related/Project Work 1 - Sem 7/Saved Models/HY_Model.h5")

"""### Plot the graphs"""

plot_graphs(HY_history, "accuracy")
plot_graphs(HY_history, "loss")

"""### Evaluation of Model"""

model_evaluate(HYmodel, [0, 1, 2, 3], testX, testHY)